let data = [
  {
    name: "Massachusetts Institute of Technology",
    sat: 1540,
    ielts: 7,
    acc: 3,
    tuition: "57,986",
    location: "Massachusetts, USA",
    ranking: 3,
    gpa: 3.5,
    img: "/mit.png",
    description:
      "“Mind and Hand” is the thought-provoking motto of the Massachusetts Institute of Technology, known also as MIT. This motto enigmatically encapsulates this famous institution’s mission to advance knowledge in science, technology and areas of scholarship that can help to make the world a better place. \n At its founding in 1861, MIT was initially a small community of problem-solvers and science lovers eager to bring their knowledge to bear on the world. Today, MIT has evolved into an educational behemoth, with some 1,000 faculty members and more than 11,000 undergraduate and graduate students. ",
  },
  {
    name: "Harvard University",
    sat: 1520,
    ielts: 7,
    acc: 3.2,
    tuition: "55,473",
    location: "California, USA",
    ranking: 4,
    gpa: 3.72,
    img: "/harvard.png",
    description:
      "Harvard University is devoted to excellence in teaching, learning, and research, and to developing leaders in many disciplines who make a difference globally. Harvard faculty are engaged with teaching and research to push the boundaries of human knowledge. The University has twelve degree-granting Schools in addition to the Radcliffe Institute for Advanced Study. \nEstablished in 1636, Harvard is the oldest institution of higher education in the United States. The University, which is based in Cambridge and Boston, Massachusetts, has an enrollment of over 20,000 degree candidates, including undergraduate, graduate, and professional students. Harvard has more than 360,000 alumni around the world.",
  },
  {
    name: "Imperial College London",
    sat: 1200,
    ielts: 6.5,
    acc: 14.3,
    tuition: "35000",
    location: "London United Kingdom",
    ranking: 2,
    gpa: 3.6,
    img: "/icl.png",
    description:
      "Imperial College London is a prestigious public research university located in London, England. It was established in 1907 and is renowned for its focus on science, engineering, medicine, and business. The institution consistently ranks among the top universities globally and is known for its rigorous academic programs, innovative research, and strong industry connections. It fosters a diverse and dynamic environment, attracting students and faculty from around the world. The campus is situated in the heart of London, offering students access to a vibrant city and numerous professional opportunities.. ",
  },
  {
    name: "University of Oxford",
    sat: 1470,
    ielts: 7,
    acc: 17,
    tuition: "41000",
    location: "London United Kingdom",
    ranking: 3,
    gpa: 3.5,
    img: "/oxford.png",
    description:
      "The University of Oxford, located in Oxford, England, is one of the world's oldest and most prestigious universities. It was founded in the 12th century and has a rich history of academic excellence and innovation. The university is composed of 39 autonomous colleges and six permanent private halls, each with its own distinct character and traditions. Oxford is renowned for its rigorous admission process, diverse academic programs, and distinguished faculty. It offers undergraduate, graduate, and professional degrees across a wide range of disciplines. The university's research output and global influence contribute significantly to various fields, including science, humanities, and social sciences.",
  },
  {
    name: "University of Cambridge",
    sat: 1460,
    ielts: 7,
    acc: 20,
    tuition: "16700",
    location: "London United Kingdom",
    ranking: 5,
    gpa: 3.2,
    img: "/cambridge.png",
    description:
      "The University of Cambridge, located in Cambridge, England, is one of the world's leading institutions of higher education. Founded in 1209, it is renowned for its long tradition of academic excellence and research. The university comprises 31 autonomous colleges, each offering a unique environment for learning and scholarly pursuit. Cambridge offers a broad range of undergraduate and graduate programs across various fields, including science, humanities, social sciences, and engineering. It is known for its rigorous academic standards, distinguished faculty, and significant contributions to research and innovation. The university also has a rich history of notable alumni, including numerous Nobel laureates, world leaders, and influential thinkers.",
  },
  {
    name: "Stanford university",
    sat: 1470,
    ielts: 7,
    acc: 14,
    tuition: "60000",
    location: "Stanford United States",
    ranking: 6,
    gpa: 3.5,
    img: "/standford.png",
    description:
      "Stanford University, located in Stanford, California, is a leading private research university founded in 1885. Renowned for its rigorous academic programs and innovation, it offers a wide range of undergraduate and graduate degrees across various fields including humanities, social sciences, natural sciences, and engineering. Stanford is known for its entrepreneurial spirit, with a strong emphasis on interdisciplinary research and close ties to Silicon Valley, which foster a culture of innovation and technology development. The university's campus is also notable for its beautiful architecture and extensive facilities. Stanford's distinguished faculty and alumni include numerous Nobel laureates, entrepreneurs, and influential leaders in various fields.",
  },
  {
    name: "Eth Zurich",
    sat: 1400,
    ielts: 6.5,
    acc: 27,
    tuition: "1670",
    location: "Zurich Switzerland",
    ranking: 7,
    gpa: 3.3,
    img: "/zurich.png",
    description:
      "ETH Zurich (Swiss Federal Institute of Technology Zurich) is a prestigious and world-renowned research university located in Zurich, Switzerland. It is known for its cutting-edge research, especially in engineering, technology, and the natural sciences. Established in 1855, ETH Zurich consistently ranks among the top universities globally. The institution is celebrated for its high academic standards, innovative research, and strong industry connections. It has a strong emphasis on interdisciplinary collaboration and is home to numerous research institutes and laboratories. The university also boasts a diverse and international student body.",
  },
  {
    name: "National University of Singapore ",
    sat: 1250,
    ielts: 6,
    acc: 10,
    tuition: "15000",
    location: "Singapore Singapore",
    ranking: 7,
    gpa: 3.6,
    img: "/nus.png",
    description:
      "The National University of Singapore (NUS) is a leading global university located in Singapore. Established in 1905, it is renowned for its research excellence, rigorous academic programs, and strong emphasis on innovation and interdisciplinary learning. NUS offers a broad range of undergraduate and graduate programs across various fields, including engineering, science, business, social sciences, and humanities. The university is known for its vibrant campus life, diverse student body, and strong connections with industry and research institutions. NUS consistently ranks among the top universities in Asia and the world.",
  },
  {
    name: "University PSL",
    sat: 1100,
    ielts: 5,
    acc: 70,
    tuition: "5600",
    location: "Paris France",
    ranking: 24,
    gpa: 3,
    img: "/psl_uni.png",
    description:
      "Université PSL (Paris Sciences et Lettres) is a prestigious and multidisciplinary higher education and research institution based in Paris, France. It was established in 2010 and is known for its rigorous academic programs and strong emphasis on research across a wide range of disciplines. PSL brings together several renowned institutions, including.The university offers a diverse range of programs in the humanities, social sciences, natural sciences, and engineering. PSL is distinguished by its strong research output, international collaborations, and a commitment to fostering innovation and critical thinking.",
  },
  {
    name: "Delft University",
    sat: 1100,
    ielts: 6.5,
    acc: 82,
    tuition: "11000",
    location: "Delft Netherlands",
    ranking: 49,
    gpa: 3,
    img: "/delft_uni.png",
    description:
      "Delft University of Technology (TU Delft) is a prominent technical university in Delft, Netherlands, founded in 1842. It is acclaimed for its engineering and technology programs, offering a wide range of degrees in areas like engineering, architecture, and industrial design. The university emphasizes research and innovation, with advanced facilities and strong industry collaborations. TU Delft is consistently recognized among the world's leading technical institutions.",
  },
  {
    name: "Korea Advanced Institute of Science and Technology (KAIST)",
    sat: 1400,
    ielts: 6.5,
    acc: 32,
    tuition: "4000",
    location: "Daejeon, South Korea",
    ranking: 33,
    gpa: 3.5,
    img: "/kaist.png",
    description:
      "KAIST, established in 1971, is a premier science and technology research university in South Korea. Located in Daejeon, KAIST is renowned for its cutting-edge research and innovation in engineering, natural sciences, and technology. The university provides a range of undergraduate and graduate programs and is recognized for its significant contributions to technological advancement.",
  },
  {
    name: "Yonsei University",
    sat: 1300,
    ielts: 6.5,
    acc: 28,
    tuition: "5000",
    location: "Seoul, South Korea",
    ranking: 72,
    gpa: 3.3,
    img: "/yonsei.png",
    description:
      "Founded in 1885, Yonsei University is one of South Korea's oldest and most prestigious institutions. Located in Seoul, it offers a wide range of undergraduate and graduate programs, with a strong emphasis on research and international collaboration. Yonsei is known for its beautiful campus, diverse student body, and significant impact in the global academic community.",
  },
  {
    name: "Seoul National University (SNU)",
    sat: 1350,
    ielts: 6.5,
    acc: 30,
    tuition: "4000",
    location: "Seoul, South Korea",
    ranking: 49,
    gpa: 3.4,
    img: "/seoul_national.png",
    description:
      "Seoul National University, established in 1946, is South Korea's leading national university. It offers a comprehensive range of undergraduate and graduate programs across multiple disciplines. Known for its rigorous academic standards and research excellence, SNU is a key player in South Korea's higher education landscape and consistently ranks among the top universities in Asia.",
  },
  {
    name: "University of Arizona",
    sat: 1200,
    ielts: 6.5,
    acc: 28,
    tuition: "38000",
    location: "Tucson, Arizona, USA",
    ranking: 91,
    gpa: 3.4,
    img: "/uarizona.png",
    description:
      "The University of Arizona, founded in 1885, is a public research university located in Tucson, Arizona. It offers a wide range of undergraduate and graduate programs and is known for its strong research output, particularly in space sciences, engineering, and health sciences. The university provides a vibrant campus life and is recognized for its commitment to innovation and community engagement.",
  },
  {
    name: "Hong Kong University of Science and Technology (HKUST)",
    sat: 1450,
    ielts: 6.5,
    acc: 32,
    tuition: "30000",
    location: "Hong Kong",
    ranking: 33,
    gpa: 3.5,
    img: "/hkust.jpg",
    description:
      "HKUST, founded in 1991, is a leading global university located in Hong Kong. It is well-known for its emphasis on science, engineering, and business education. The university is recognized for its cutting-edge research, innovative teaching methods, and strong international partnerships. HKUST consistently ranks among the top universities in Asia and worldwide.",
  },
  {
    name: "National University of Singapore (NUS)",
    sat: 1400,
    ielts: 6.5,
    acc: 30,
    tuition: "8000",
    location: "Singapore",
    ranking: 11,
    gpa: 3.4,
    img: "/nus.png",
    description:
      "Founded in 1905, NUS is Singapore's oldest and most prestigious university. It offers a broad range of undergraduate and graduate programs and is renowned for its research excellence, particularly in science, technology, and business. NUS is known for its strong industry connections, diverse student body, and commitment to global engagement.",
  },
  {
    name: "New York University Abu Dhabi (NYU AD)",
    sat: 1450,
    ielts: 7.0,
    acc: 32,
    tuition: "75000",
    location: "Abu Dhabi, United Arab Emirates",
    ranking: 30,
    gpa: 3.5,
    img: "/nyuad.png",
    description:
      "NYU Abu Dhabi, established in 2010, is a global campus of New York University located in Abu Dhabi. It offers a liberal arts education with a strong emphasis on global perspectives and interdisciplinary learning. The university is known for its diverse student body, innovative research opportunities, and its role as a hub for international dialogue and understanding.",
  },
  {
    name: "Carnegie Mellon University Qatar",
    sat: 1400,
    ielts: 7.0,
    acc: 30,
    tuition: "35000",
    location: "Doha, Qatar",
    ranking: 51,
    gpa: 3.5,
    img: "/CMU_Q.png",
    description:
      "Carnegie Mellon University Qatar, established in 2004, is the branch of Carnegie Mellon University located in Doha, Qatar. It offers a range of programs in business, computer science, and information systems. Known for its high academic standards and strong connections with industry, CMU Qatar provides a rigorous education with a global perspective.",
  },
  {
    name: "University of Pennsylvania (UPenn)",
    sat: 1480,
    ielts: 7.0,
    acc: 40,
    tuition: "55000",
    location: "Philadelphia, Pennsylvania, USA",
    ranking: 8,
    gpa: 3.7,
    img: "/upenn.png",
    description:
      "The University of Pennsylvania, founded in 1740, is an Ivy League university located in Philadelphia, Pennsylvania. UPenn offers a wide range of undergraduate and graduate programs and is known for its commitment to interdisciplinary education, research excellence, and influential faculty. It consistently ranks among the top universities in the world.",
  },
  {
    name: "Brown University",
    sat: 1450,
    ielts: 7.0,
    acc: 40,
    tuition: "57000",
    location: "Providence, Rhode Island, USA",
    ranking: 14,
    gpa: 3.6,
    img: "/brown.png",
    description:
      "Brown University, established in 1764, is a private Ivy League university located in Providence, Rhode Island. Known for its open curriculum and commitment to student-centered learning, Brown offers a broad range of programs and emphasizes interdisciplinary studies and research. The university is renowned for its diverse academic environment and strong community.",
  },
  {
    name: "University of Toronto",
    sat: 1400,
    ielts: 6.5,
    acc: 33,
    tuition: "60000",
    location: "Toronto, Ontario, Canada",
    ranking: 19,
    gpa: 3.6,
    img: "/toronto.png",
    description:
      "The University of Toronto, founded in 1827, is Canada's leading university located in Toronto, Ontario. It offers a wide range of programs and is known for its research excellence, diverse academic offerings, and vibrant campus life. The university consistently ranks among the top universities globally for its academic and research achievements.",
  },
  {
    name: "University of British Columbia (UBC)",
    sat: 1350,
    ielts: 6.5,
    acc: 32,
    tuition: "53000",
    location: "Vancouver, British Columbia, Canada",
    ranking: 34,
    gpa: 3.5,
    img: "/ubc.png",
    description:
      "UBC, founded in 1908, is a major public research university located in Vancouver, British Columbia. Known for its strong emphasis on research and innovation, UBC offers a broad range of undergraduate and graduate programs. The university is recognized for its beautiful campus, strong industry connections, and commitment to global engagement.",
  },
  {
    name: "McGill University",
    sat: 1300,
    ielts: 6.5,
    acc: 30,
    tuition: "47000",
    location: "Montreal, Quebec, Canada",
    ranking: 35,
    gpa: 3.4,
    img: "/mcgill.png",
    description:
      "McGill University, established in 1821, is one of Canada's top universities located in Montreal, Quebec. Known for its strong research programs and diverse academic offerings, McGill attracts students from around the world. The university is renowned for its rigorous academic standards, vibrant campus life, and global impact.",
  },
  {
    name: "University of Alberta",
    sat: 1250,
    ielts: 6.5,
    acc: 30,
    tuition: "25000",
    location: "Edmonton, Alberta, Canada",
    ranking: 119,
    gpa: 3.3,
    img: "/ualberta.png",
    description:
      "The University of Alberta, founded in 1908, is a leading public research university located in Edmonton, Alberta. It offers a diverse range of undergraduate and graduate programs and is known for its research strengths in fields such as science, engineering, and health sciences. The university is committed to providing a high-quality education and fostering innovation.",
  },
  {
    name: "University of Waterloo",
    sat: 1300,
    ielts: 6.5,
    acc: 31,
    tuition: "25000",
    location: "Waterloo, Ontario, Canada",
    ranking: 173,
    gpa: 3.4,
    img: "/uwaterloo.png",
    description:
      "The University of Waterloo, established in 1957, is a renowned public research university located in Waterloo, Ontario. Known for its co-op programs and innovative approach to education, Waterloo offers a range of programs across various disciplines. It is recognized for its strong ties to industry and its emphasis on experiential learning and research.",
  },
  {
    "name": "California Institute of Technology",
    "sat": 1530,
    "ielts": 7.5,
    "acc": 4.0,
    "tuition": "58500",
    "location": "Pasadena, California, USA",
    "ranking": 10,
    "gpa": 3.9,
    "img": "/caltech.png",
    "description": "California Institute of Technology, founded in 1891, is a private research university in Pasadena, California. Known for its cutting-edge research and emphasis on science and engineering, Caltech offers a rigorous academic environment and is renowned for its strong focus on technological innovation."
},
{
  "name": "University of California, Berkeley",
  "sat": 1400,
  "ielts": 7.0,
  "acc": 15,
  "tuition": "47000",
  "location": "Berkeley, California, USA",
  "ranking": 32,
  "gpa": 3.8,
  "img": "/uc_berkeley.png",
  "description": "University of California, Berkeley, established in 1868, is a public research university in Berkeley, California. Known for its distinguished faculty and rigorous academic programs, UC Berkeley offers a broad range of disciplines and emphasizes research and public service."
},
{
    "name": "Cornell University",
    "sat": 1480,
    "ielts": 7.0,
    "acc": 9,
    "tuition": "59000",
    "location": "Ithaca, New York, USA",
    "ranking": 18,
    "gpa": 3.7,
    "img": "/cornell.png",
    "description": "Cornell University, founded in 1865, is an Ivy League private university in Ithaca, New York. It offers a wide range of programs with a strong emphasis on research and interdisciplinary studies. Cornell is known for its diverse academic offerings and vibrant campus life."
},
{
    "name": "The University of Sydney",
    "sat": 1350,
    "ielts": 6.5,
    "acc": 30,
    "tuition": "50000",
    "location": "Sydney, New South Wales, Australia",
    "ranking": 42,
    "gpa": 3.5,
    "img": "/sydney.png",
    "description": "The University of Sydney, established in 1850, is a public research university located in Sydney, Australia. It is known for its strong research programs and diverse academic offerings, with a focus on fostering a global perspective and a commitment to community engagement."
},
{
    "name": "The University of New South Wales",
    "sat": 1300,
    "ielts": 6.5,
    "acc": 20,
    "tuition": "49000",
    "location": "Sydney, New South Wales, Australia",
    "ranking": 43,
    "gpa": 3.5,
    "img": "/unsw.png",
    "description": "The University of New South Wales (UNSW), founded in 1949, is a public research university in Sydney, Australia. Known for its strong emphasis on research and innovation, UNSW offers a wide range of programs and is committed to providing a high-quality education."
},
{
    "name": "Tsinghua University",
    "sat": 1450,
    "ielts": 6.5,
    "acc": 12,
    "tuition": "8000",
    "location": "Beijing, China",
    "ranking": 11,
    "gpa": 3.6,
    "img": "/tsinghua.png",
    "description": "Tsinghua University, established in 1911, is a prestigious research university in Beijing, China. Known for its strengths in engineering and technology, Tsinghua is a leading institution in China with a global reputation for academic excellence and research."
},
{
    "name": "University of Chicago",
    "sat": 1500,
    "ielts": 7.5,
    "acc": 6,
    "tuition": "62000",
    "location": "Chicago, Illinois, USA",
    "ranking": 6,
    "gpa": 3.8,
    "img": "/uchicago.png",
    "description": "The University of Chicago, founded in 1890, is a private research university in Chicago, Illinois. It is known for its rigorous academic programs and influential research, particularly in economics and social sciences. The university fosters a strong intellectual community."
},
{
    "name": "Princeton University",
    "sat": 1480,
    "ielts": 7.0,
    "acc": 5,
    "tuition": "58000",
    "location": "Princeton, New Jersey, USA",
    "ranking": 22,
    "gpa": 3.9,
    "img": "/princeton.png",
    "description": "Princeton University, established in 1746, is a private Ivy League university in Princeton, New Jersey. Known for its emphasis on undergraduate education and research, Princeton offers a broad range of programs and is renowned for its strong academic environment."
},
{
    "name": "Yale University",
    "sat": 1460,
    "ielts": 7.0,
    "acc": 6,
    "tuition": "58000",
    "location": "New Haven, Connecticut, USA",
    "ranking": 23,
    "gpa": 3.9,
    "img": "/yale.png",
    "description": "Yale University, founded in 1701, is a private Ivy League institution located in New Haven, Connecticut. It is renowned for its outstanding academic programs, strong research focus, and commitment to undergraduate education and community engagement."
},
{
    "name": "Johns Hopkins University",
    "sat": 1480,
    "ielts": 7.0,
    "acc": 9,
    "tuition": "58000",
    "location": "Baltimore, Maryland, USA",
    "ranking": 32,
    "gpa": 3.8,
    "img": "/jhu.png",
    "description": "Johns Hopkins University, established in 1876, is a private research university in Baltimore, Maryland. Known for its leading research programs, particularly in medicine and public health, Johns Hopkins offers a robust academic environment and a commitment to innovation."
},
{
    "name": "The University of Edinburgh",
    "sat": 1300,
    "ielts": 6.5,
    "acc": 10,
    "tuition": "25000",
    "location": "Edinburgh, Scotland",
    "ranking": 27,
    "gpa": 3.5,
    "img": "/edinburgh.png",
    "description": "The University of Edinburgh, founded in 1582, is a public research university in Edinburgh, Scotland. It is known for its strong research output and a broad range of academic disciplines, offering a historic and vibrant academic environment."
},
{
    "name": "Technical University of Munich",
    "sat": 1400,
    "ielts": 6.5,
    "acc": 8,
    "tuition": "15000",
    "location": "Munich, Germany",
    "ranking": 28,
    "gpa": 3.6,
    "img": "/tum.png",
    "description": "The Technical University of Munich (TUM), founded in 1868, is a leading public research university in Munich, Germany. Known for its emphasis on engineering and technology, TUM is recognized for its strong research programs and innovative approach to education."
},
{
    "name": "The University of Tokyo",
    "sat": 1400,
    "ielts": 6.5,
    "acc": 35,
    "tuition": "5000",
    "location": "Tokyo, Japan",
    "ranking": 36,
    "gpa": 3.6,
    "img": "/utokyo.png",
    "description": "The University of Tokyo, established in 1877, is Japan's leading public research university located in Tokyo. It is renowned for its strong academic programs and research excellence, offering a comprehensive range of disciplines."
},
{
    "name": "Columbia University",
    "sat": 1480,
    "ielts": 7.0,
    "acc": 3,
    "tuition": "63000",
    "location": "New York City, New York, USA",
    "ranking": 34,
    "gpa": 3.9,
    "img": "/columbia.png",
    "description": "Columbia University, founded in 1754, is an Ivy League private university located in New York City. Known for its rigorous academic programs and strong research focus, Columbia offers a prestigious and intellectually stimulating environment."
},
{
    "name": "The University of Manchester",
    "sat": 1300,
    "ielts": 6.5,
    "acc": 25,
    "tuition": "27000",
    "location": "Manchester, England",
    "ranking": 55,
    "gpa": 3.5,
    "img": "/manchester.png",
    "description": "The University of Manchester, established in 1824, is a public research university in Manchester, England. Known for its strong research programs and diverse academic disciplines, it offers a dynamic and inclusive academic environment."
},
{
    "name": "University of Birmingham",
    "sat": 1350,
    "ielts": 6.5,
    "acc": 80,
    "tuition": "25000",
    "location": "Birmingham, England, UK",
    "ranking": 79,
    "gpa": 3.0,
    "img": "/birmingham.png",
    "description": "The University of Birmingham, founded in 1900, is a public research university located in Birmingham, England. It is a member of the prestigious Russell Group and offers a wide range of undergraduate and postgraduate programs. The university is known for its research output and vibrant campus life."
},
{
    "name": "Lund University",
    "sat": 1400,
    "ielts": 7.0,
    "acc": 75,
    "tuition": "15000",
    "location": "Lund, Sweden",
    "ranking": 87,
    "gpa": 3.2,
    "img": "/lund.png",
    "description": "Lund University, established in 1666, is one of Scandinavia's oldest and most prestigious universities. Located in Lund, Sweden, it offers a wide array of programs and is recognized for its high-quality research and education, particularly in science and technology."
},
{
    "name": "Universidade de São Paulo",
    "sat": 1300,
    "ielts": 6.0,
    "acc": 70,
    "tuition": "Free",
    "location": "São Paulo, Brazil",
    "ranking": 115,
    "gpa": 3.0,
    "img": "/usp.png",
    "description": "Universidade de São Paulo (USP), founded in 1934, is a public university located in São Paulo, Brazil. It is the largest and most prestigious university in Brazil, known for its extensive research output and comprehensive range of academic programs."
},
{
    "name": "Lomonosov Moscow State University",
    "sat": 1420,
    "ielts": 7.0,
    "acc": 60,
    "tuition": "5000",
    "location": "Moscow, Russia",
    "ranking": 84,
    "gpa": 3.4,
    "img": "/lomonosov.png",
    "description": "Lomonosov Moscow State University, established in 1755, is a public research university in Moscow, Russia. It is the highest-ranking Russian educational institution and is renowned for its comprehensive research programs and influential alumni."
},
{
    "name": "The University of Adelaide",
    "sat": 1370,
    "ielts": 6.5,
    "acc": 75,
    "tuition": "32000",
    "location": "Adelaide, South Australia, Australia",
    "ranking": 106,
    "gpa": 3.1,
    "img": "/adelaide.png",
    "description": "The University of Adelaide, established in 1874, is a public university in Adelaide, Australia. It is a member of the Group of Eight and is known for its high-quality education and research, particularly in the sciences and engineering."
},
{
    "name": "Tokyo Institute of Technology",
    "sat": 1450,
    "ielts": 7.0,
    "acc": 35,
    "tuition": "4000",
    "location": "Tokyo, Japan",
    "ranking": 56,
    "gpa": 3.5,
    "img": "/tokyo_tech.png",
    "description": "Tokyo Institute of Technology, established in 1881, is a top-tier public research university in Tokyo, Japan. It specializes in science and technology and is renowned for its research output and contributions to innovation."
},
{
    "name": "Boston University",
    "sat": 1420,
    "ielts": 7.0,
    "acc": 22,
    "tuition": "58000",
    "location": "Boston, Massachusetts, USA",
    "ranking": 57,
    "gpa": 3.6,
    "img": "/boston.png",
    "description": "Boston University (BU), founded in 1839, is a private research university in Boston, Massachusetts. Known for its extensive research activities and diverse academic offerings, BU provides a dynamic environment for students and faculty."
},
{
    "name": "Georgia Institute of Technology",
    "sat": 1440,
    "ielts": 7.0,
    "acc": 21,
    "tuition": "33000",
    "location": "Atlanta, Georgia, USA",
    "ranking": 44,
    "gpa": 3.7,
    "img": "/georgia_tech.png",
    "description": "The Georgia Institute of Technology, commonly referred to as Georgia Tech, is a public research university in Atlanta, Georgia. Established in 1885, it is renowned for its engineering and technology programs and is a leading institution in innovation and research."
},
{
    "name": "Freie Universität Berlin",
    "sat": 1350,
    "ielts": 6.5,
    "acc": 50,
    "tuition": "Free",
    "location": "Berlin, Germany",
    "ranking": 118,
    "gpa": 3.2,
    "img": "/freie_berlin.png",
    "description": "Freie Universität Berlin, founded in 1948, is a premier research university located in Berlin, Germany. It is known for its strong emphasis on research and offers a wide range of academic programs across various disciplines."
},
{
    "name": "Purdue University",
    "sat": 1380,
    "ielts": 6.5,
    "acc": 58,
    "tuition": "29000",
    "location": "West Lafayette, Indiana, USA",
    "ranking": 53,
    "gpa": 3.5,
    "img": "/purdue.png",
    "description": "Purdue University, founded in 1869, is a public research university in West Lafayette, Indiana. It is renowned for its engineering and technology programs and has a strong emphasis on research and innovation."
},
{
    "name": "Australian National University",
    "sat": 1400,
    "ielts": 7.0,
    "acc": 35,
    "tuition": "31000",
    "location": "Canberra, Australian Capital Territory, Australia",
    "ranking": 29,
    "gpa": 3.5,
    "img": "/anu.png",
    "description": "The Australian National University (ANU), established in 1946, is a public research university located in Canberra, Australia. It is one of the top universities in Australia, known for its research output and academic excellence across various disciplines."
},
{
    "name": "University of British Columbia",
    "sat": 1430,
    "ielts": 7.0,
    "acc": 52,
    "tuition": "36000",
    "location": "Vancouver, British Columbia, Canada",
    "ranking": 34,
    "gpa": 3.6,
    "img": "/ubc.png",
    "description": "The University of British Columbia (UBC), founded in 1908, is a public research university located in Vancouver, Canada. It is renowned for its strong research programs and diverse academic offerings, particularly in the sciences and humanities."
},
{
    "name": "New York University",
    "sat": 1440,
    "ielts": 7.0,
    "acc": 20,
    "tuition": "56000",
    "location": "New York City, New York, USA",
    "ranking": 35,
    "gpa": 3.7,
    "img": "/nyu.png",
    "description": "New York University (NYU), established in 1831, is a private research university located in New York City. It is known for its comprehensive academic programs, extensive research activities, and vibrant urban campus environment."
},
{
    "name": "Monash University",
    "sat": 1380,
    "ielts": 6.5,
    "acc": 55,
    "tuition": "30000",
    "location": "Melbourne, Victoria, Australia",
    "ranking": 58,
    "gpa": 3.4,
    "img": "/monash.png",
    "description": "Monash University, established in 1958, is a public research university located in Melbourne, Australia. It is a member of the Group of Eight and is known for its strong emphasis on research and high-quality education, particularly in the sciences and engineering."
}
];

export default data;
